# Generated by Django 5.1 on 2024-08-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariovendido',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
