# Generated by Django 5.1 on 2026-02-25 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0003_remove_inventario_numero_identificador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio_venta', models.IntegerField()),
                ('codigo_barras', models.CharField(max_length=255, unique=True)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diarios.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_unitario', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('anulada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diarios.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='DiarioVendido',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='devolucion',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='motivo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devolucion',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='diarios.producto'),
            preserve_default=False,
        ),
    ]
